#!/bin/bash

# Set default values for environment variables
: "${HTTP_URL:=https://connect.prusa3d.com/c/snapshot}"
: "${DELAY_SECONDS:=10}"
: "${LONG_DELAY_SECONDS:=60}"
# FINGERPRINT can be a random string with at least 16 characters.  Use a UUID here.
# : "${FINGERPRINT:=123456789012345678}"
# CAMERA_TOKEN generated by the Connect server
# : "${CAMERA_TOKEN:=connect-token-here}"


# Read the secrets file for FINGERPRINT and CAMERA_TOKEN
if [ -f .secrets ]; then
    # Read the secrets file and export variables
    set -a
    source .secrets
    set +a
else
    echo "Secrets file '.secrets' must exist and contain FINGERPRINT and CAMERA_TOKEN values."
    echo "FINGERPRINT=<a UUID unique to this camera instance>"
    echo "CAMERA_TOKEN=<token assigned by Prusa Connect>"
    exit 1
fi

echo "Starting Image Capture for Prusa Connect\n"
echo "HTTP_URL: $HTTP_URL"
echo "DELAY_SECONDS: $DELAY_SECONDS"
echo "LONG_DELAY_SECONDS: $LONG_DELAY_SECONDS"
echo "FINGERPRINT: $FINGERPRINT"
# echo "CAMERA_TOKEN: $CAMERA_TOKEN"

while true; do
    # Image capture.
    # -q = JPEG quality.  Keep it low for file size reasons, -t is timeout. 1 = 1 sec, so command runs quickly.
    rpicam-jpeg -q 50 --width 800 --height 600 -t 1 -o /tmp/3d_still.jpg
     # If no error, upload it.
     if [ $? -eq 0 ]; then
         # POST the image to the HTTP URL using curl
         curl -k -X PUT "$HTTP_URL" \
             -H "accept: */*" \
             -H "content-type: image/jpg" \
             -H "fingerprint: $FINGERPRINT" \
             -H "token: $CAMERA_TOKEN" \
             --data-binary "@/tmp/3d_still.jpg" \
             --no-progress-meter \
             --compressed

        # Reset delay to the normal value
        DELAY=$DELAY_SECONDS
    else
        echo "Error capturing image.  Will retry in ${LONG_DELAY_SECONDS}s..."
        # Set delay to the longer value
        DELAY=$LONG_DELAY_SECONDS
    fi

    sleep "$DELAY"
done