#!/bin/bash

# Set default values for environment variables
: "${HTTP_URL:=https://connect.prusa3d.com/c/snapshot}"
: "${DELAY_SECONDS:=10}"
: "${LONG_DELAY_SECONDS:=60}"
# FINGERPRINT can be a random string with at least 16 characters
# : "${FINGERPRINT:=123456789012345678}"
# CAMERA_TOKEN generated by the Connect server
# : "${CAMERA_TOKEN:=connect-token-here}"


# Source the secrets file if it exists
if [ -f .secrets ]; then
    # Read the secrets file and export variables
    set -a
    source .secrets
    set +a
fi

# Print all environment variables
echo "=== Environment Variables ==="
echo "HTTP_URL: $HTTP_URL"
echo "DELAY_SECONDS: $DELAY_SECONDS"
echo "LONG_DELAY_SECONDS: $LONG_DELAY_SECONDS"
echo "FINGERPRINT: $FINGERPRINT"
echo "CAMERA_TOKEN: $CAMERA_TOKEN"
echo "=========================="





# while true; do
#     # Grab a frame from libcamera-still with the highest resolution
#     # that is displayed on Prusa Connect: 1704 x 1278 for a 4:3 image
#     # Setting the quality to 80 saves almost 50% in file size for
#     # very little decrease in quality. Set to taste!
#     # If you need to rotate the image 180° add `--rotate 180`
#     # (One user reported needing to make this `--camera.rotate 180` instead!)
#     libcamera-still -v 0 --immediate --width 2274 --height 1280 -q 80 -o /tmp/output.jpg

#     # If no error, upload it.
#     if [ $? -eq 0 ]; then
#         # POST the image to the HTTP URL using curl
#         curl -k -X PUT "$HTTP_URL" \
#             -H "accept: */*" \
#             -H "content-type: image/jpg" \
#             -H "fingerprint: $FINGERPRINT" \
#             -H "token: $CAMERA_TOKEN" \
#             --data-binary "@/tmp/output.jpg" \
#             --no-progress-meter \
#             --compressed

#         # Reset delay to the normal value
#         DELAY=$DELAY_SECONDS
#     else
#         echo "libcamera-still returned an error, retrying after ${LONG_DELAY_SECONDS}s..."
        
#         # Set delay to the longer value
#         DELAY=$LONG_DELAY_SECONDS
#     fi

#     sleep "$DELAY"
# done